services:
  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
