hwi_oauth:
  resource_owners:
    any_name:
      type: github
      client_id: %env(OAUTH_GITHUB_CLIENT_ID)%
      client_secret: %env(OAUTH_GITHUB_CLIENT_SECRET)%
      scope: "user:email,public_repo"
